### PR TITLE
Make software update und operating system display work on arch linux

### PR DESCRIPTION
**Pull request by julbrygd**
Hi,

I made a few changes, that Kimchi can make software updates on an Arch Linux and also displays the Arch Linux os information.

Reagards Stephan

### CODE REVIEW

**Comment by julbrygd** [comment]
I forgot to say that I maintain the AUR package for Kimchi.

**Comment by alinefm** [comment]
Hi @julbrygd,

Thanks for your patches. We really want to have more and more Linux distribution support.
And I am really glad to know you support the AUR package for Kimchi. Thanks again!

Could you, please, follow the instructions at https://github.com/kimchi-project/kimchi/wiki/how-to-contribute to get your patches reviewed and merged?

Unfortunately, we don't work based on pull requests.

**Comment by julbrygd** [comment]
Hi,

I have a problem with the configuration for git. On my installation git give me following error message:
git askreview *.patch
fatal: ambiguous argument '–annotate': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
format-patch -o /tmp/0JdvG08LkU –annotate *.patch: command returned error: 128

Can you please help me?

Regards Stephan

**Comment by laggarcia** [comment]
Stephan,

git askreview seems to be a git alias configured in your system (at least, I cannot find it in my system, even though I am not using Arch Linux).

From the error message, it seems it is calling git format-patch at some point. If I am following things correctly, the issue here is that you are passing *.patch files to git format-patch, which isn't needed. You can pass directly the git revision hash.

So, based on your pull request, I think the command you should be using would be something like:

git askreview 5475f53dc893563385dc8e7333949fabda0dccff

If this doesn't work, I can help you out without using askreview (as I really don't know the syntax of this git alias). If you join #kimchi @ OFTC, it might be easier to help you.

**Comment by alinefm** [comment]
@julbrygd ops... seems we have a typo in the wiki page

The correct is "--annotate" instead of "-annotate".
Could you verify it works for you?

**Comment by julbrygd** [comment]
Hi,

I change the config, but I get the error again:
git askreview *.patch
fatal: ambiguous argument '–-annotate': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
format-patch -o /tmp/PfyC6lCpvQ –-annotate: command returned error: 128

could this be a problem with my git version:
git --version
git version 2.4.3


Regards Stephan

**Comment by alinefm** [comment]
Hi @julbrygd,

Seems there is a big minus in your configuration (look the first one): '–-annotate'. Replace both ''–-" to '--'

**Pull request closed without merging**
