### PR TITLE
Update kimchid.service.fedora

### PR DESCRIPTION
**Pull request by vmorris**
Just applied this to Fedora 21, works great.

### CODE REVIEW

**Comment by laggarcia** [comment]
@vmorris, what issue were you seeing? Others seem to be using Kimchi service in Fedora 21 without issues...

**Comment by vmorris** [comment]
@laggarcia I have to wonder if they bothered to apply the systemd unit file provided.. Running configure set prefix = /usr/local and that's where everything landed after make install.

[vance@holocron kimchi-master]$ ls /usr/local/etc/kimchi/
distros.d        kimchi.conf     nginx.conf.in
kimchi-cert.pem  kimchi-key.pem  nginx_kimchi.conf

[vance@holocron kimchi-master]$ ls /usr/local/bin/kimchid 
/usr/local/bin/kimchid

**Comment by alinefm** [comment]
@vmorris Unfortunatelly we don't work based on pull requests.
Please, check https://github.com/kimchi-project/kimchi/wiki/How-to-Contribute for more details.

**Comment by alinefm** [comment]
@vmorris Also you, probably, are facing issues because you haven't used the "--system" option to autogen.

sudo ./autogen.sh --system && sudo make

**Pull request closed without merging**
